const { contextBridge, ipcRenderer } = require('electron');
const { t, DICTS } = require('./i18n');

contextBridge.exposeInMainWorld('api', {
  getInit: () => ipcRenderer.invoke('get-init-state'),
  updateSettings: (partial) => ipcRenderer.invoke('update-settings', partial),
  toggleClicking: () => ipcRenderer.invoke('toggle-clicking'),
  startClicking: (opts) => ipcRenderer.invoke('start-clicking', opts || {}),
  stopClicking: () => ipcRenderer.invoke('stop-clicking'),
  togglePause: () => ipcRenderer.invoke('toggle-pause'),
  panicStop: () => ipcRenderer.invoke('panic-stop'),
  samplePixelColor: () => ipcRenderer.invoke('sample-pixel-color'),
  listSlots: () => ipcRenderer.invoke('list-slots'),
  saveSlot: (name) => ipcRenderer.invoke('save-slot', name),
  loadSlot: (name) => ipcRenderer.invoke('load-slot', name),
  deleteSlot: (name) => ipcRenderer.invoke('delete-slot', name),
  savePreset: (p) => ipcRenderer.invoke('save-preset', p),
  deletePreset: (n) => ipcRenderer.invoke('delete-preset', n),
  renamePreset: (o) => ipcRenderer.invoke('rename-preset', o),
  duplicatePreset: (n) => ipcRenderer.invoke('duplicate-preset', n),
  applyPreset: (n) => ipcRenderer.invoke('apply-preset', n),
  seedGamePresets: () => ipcRenderer.invoke('seed-game-presets'),
  saveMacro: (m) => ipcRenderer.invoke('save-macro', m),
  deleteMacro: (id) => ipcRenderer.invoke('delete-macro', id),
  runMacro: (id) => ipcRenderer.invoke('run-macro', id),
  macroStartRecording: () => ipcRenderer.invoke('macro-start-recording'),
  macroStopRecording: () => ipcRenderer.invoke('macro-stop-recording'),
  macroSetSteps: (steps) => ipcRenderer.invoke('macro-set-steps', steps || []),
  macroAddClick: (button) => ipcRenderer.invoke('macro-add-click', button),
  macroAddKey: (key) => ipcRenderer.invoke('macro-add-key', key),
  macroAddSequence: (seq) => ipcRenderer.invoke('macro-add-sequence', seq),
  macroAddDelay: (ms) => ipcRenderer.invoke('macro-add-delay', ms),
  macroClearSteps: () => ipcRenderer.invoke('macro-clear-steps'),
  macroGetRecording: () => ipcRenderer.invoke('macro-get-recording'),
  macroShareEncode: (id) => ipcRenderer.invoke('macro-share-encode', id),
  macroShareDecode: (text) => ipcRenderer.invoke('macro-share-decode', text),
  drawZone: () => ipcRenderer.invoke('draw-zone'),
  exportPresets: () => ipcRenderer.invoke('export-presets'),
  importPresets: () => ipcRenderer.invoke('import-presets'),
  exportMacros: () => ipcRenderer.invoke('export-macros'),
  importMacros: () => ipcRenderer.invoke('import-macros'),
  clipboardWriteJson: (payload) => ipcRenderer.invoke('clipboard-write-json', payload),
  clipboardReadJson: () => ipcRenderer.invoke('clipboard-read-json'),
  getChangelog: () => ipcRenderer.invoke('get-changelog'),
  checkUpdates: () => ipcRenderer.invoke('check-updates'),
  copyText: (text) => ipcRenderer.invoke('copy-text', text),
  pickBackgroundImage: () => ipcRenderer.invoke('pick-background-image'),
  resolveBackgroundImage: (src) => ipcRenderer.invoke('resolve-background-image', src),
  resetSettings: () => ipcRenderer.invoke('reset-settings'),
  resetStats: () => ipcRenderer.invoke('reset-stats'),
  openDiagnostics: () => ipcRenderer.invoke('open-diagnostics-folder'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  revealDiscordLogo: () => ipcRenderer.invoke('reveal-discord-logo'),
  winMinimize: () => ipcRenderer.invoke('win-minimize'),
  winClose: () => ipcRenderer.invoke('win-close'),
  winPin: (p) => ipcRenderer.invoke('win-pin', p),
  setWindowMode: (mode) => ipcRenderer.invoke('set-window-mode', mode),
  setHotkeyCapture: (active) => ipcRenderer.invoke('set-hotkey-capture', !!active),
  getCursorPos: () => ipcRenderer.invoke('get-cursor-pos'),
  onStats: (cb) => ipcRenderer.on('stats-update', (e, d) => cb(d)),
  onClickState: (cb) => ipcRenderer.on('click-state', (e, d) => cb(d)),
  onMacroRan: (cb) => ipcRenderer.on('macro-ran', (e, d) => cb(d)),
  onMacroRecording: (cb) => ipcRenderer.on('macro-recording-update', (e, d) => cb(d)),
  onGoalReached: (cb) => ipcRenderer.on('goal-reached', (e, d) => cb(d)),
  onConfirmHighCps: (cb) => ipcRenderer.on('confirm-high-cps', (e, d) => cb(d)),
});

contextBridge.exposeInMainWorld('i18n', {
  t: (lang, key, vars) => t(lang, key, vars),
  dicts: DICTS
});
